name: Publish to NuGet

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  publish:
    name: Build, Tag, Push & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: TimeParser/TimeSpanParserUtil.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}} # nuget.org API key
